# Generated by Django 4.1.7 on 2023-03-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computedroute',
            options={'default_related_name': 'computed_routes', 'ordering': ['cargo', 'distance']},
        ),
        migrations.AlterField(
            model_name='computedroute',
            name='distance',
            field=models.FloatField(db_index=True),
        ),
    ]
